In [1]:
#Filtering - Using conditionals to filter rows and columns
people={
    'first':['aravind','rahul','jake'],
    'last':['reddy','reddy','chris'],
    'email':['malluriaravindreddy@gmail.com','rahulreddy@gmail.com','jakechris@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

     first   last                          email
0  aravind  reddy  malluriaravindreddy@gmail.com
1    rahul  reddy           rahulreddy@gmail.com
2     jake  chris            jakechris@gmail.com

In [5]:
df['last']=='reddy'

0     True
1     True
2    False
Name: last, dtype: bool

In [6]:
# if we want to access the dataframe with last name contains reddy 
filt=(df['last']=='reddy')

In [9]:
df[filt]
#here we had get our dataframe back and returned all of the last name 'reddy'

     first   last                          email
0  aravind  reddy  malluriaravindreddy@gmail.com
1    rahul  reddy           rahulreddy@gmail.com

In [10]:
#alternative way
df[df['last']=='reddy']

     first   last                          email
0  aravind  reddy  malluriaravindreddy@gmail.com
1    rahul  reddy           rahulreddy@gmail.com

In [11]:
df.loc[filt]

     first   last                          email
0  aravind  reddy  malluriaravindreddy@gmail.com
1    rahul  reddy           rahulreddy@gmail.com

In [14]:
# we can use loc and even can grab specific column using .loc
df.loc[filt,'email']
# 1st value filt is rows we want
# 2nd value email is column we want

0    malluriaravindreddy@gmail.com
1             rahulreddy@gmail.com
Name: email, dtype: object

In [15]:
# & -> and , | -> or
filt=(df['last']=='reddy') & (df['first']=='rahul')

In [16]:
df.loc[filt,'email']

1    rahulreddy@gmail.com
Name: email, dtype: object

In [17]:
filt=(df['last']=='reddy') | (df['first']=='rahul')

In [18]:
df.loc[filt,'email']

0    malluriaravindreddy@gmail.com
1             rahulreddy@gmail.com
Name: email, dtype: object

In [21]:
filt=(df['last']=='reddy')  | (df['first']=='rahul')

In [22]:
df.loc[~filt,'email']

2    jakechris@gmail.com
Name: email, dtype: object

In [23]:
import pandas as pd

In [33]:
df=pd.read_csv('Desktop/data/survey_results_public.csv',index_col='Respondent')
schema=pd.read_csv('Desktop/data/survey_results_schema.csv',index_col='Column')

In [42]:
df

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
11,I am a developer by profession,Yes,23.0,13,Yearly,31000.0,40070.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Django;React.js,Angular;Angular.js;Django;React.js,Just as welcome now as I felt last year,40.0,10,2
12,I am a developer by profession,No,49.0,42,Monthly,1100.0,14268.0,Spain,European Euro,EUR,...,Easy,Appropriate in length,No,Mathematics or statistics,ASP.NET;jQuery,ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,7,7
13,"I am not primarily a developer, but I write co...",Yes,53.0,14,Monthly,3000.0,38916.0,Netherlands,European Euro,EUR,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20
14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
15,I am a student who is learning to code,Yes,NaN,13,NaN,NaN,NaN,France,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
20,I am a developer by profession,Yes,40.0,18,NaN,NaN,NaN,Spain,European Euro,EUR,...,Easy,Too short,No,"Another engineering discipline (such as civil,...",Spring,Angular.js;Spring,Just as welcome now as I felt last year,50.0,22,17
21,I am a student who is learning to code,Yes,23.0,16,NaN,NaN,NaN,Belgium,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Gatsby;React.js;Spring;Vue.js,Angular;ASP.NET Core;Express;React.js;Spring,NaN,NaN,7,NaN
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
23,I am a developer by profession,Yes,27.0,14,NaN,NaN,NaN,Germany,European Euro,EUR,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Somewhat less welcome now than last year,40.0,8,3
24,I am a developer by profession,Yes,45.0,14,Yearly,85000.0,91883.0,Germany,European Euro,EUR,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,42.0,30,20
25,I am a developer by profession,No,NaN,25,Monthly,NaN,NaN,Portugal,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,23,18
26,I am a developer by profession,No,NaN,12,Yearly,94000.0,71093.0,Canada,Canadian dollar,CAD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,Django;React.js,Just as welcome now as I felt last year,40.0,17,10
27,"I used to be a developer by profession, but no...",Yes,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",Flask,Flask,Just as welcome now as I felt last year,NaN,20,20
28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
29,I am a student who is learning to code,Yes,18.0,15,NaN,NaN,NaN,Ukraine,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
30,I am a developer by profession,Yes,NaN,14,Yearly,30000.0,38778.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Express;React.js;Vue.js,Express;Vue.js,A lot less welcome now than last year,37.0,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61121,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61490,NaN,Yes,NaN,14,NaN,NaN,NaN,United Kingdom,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Ruby on Rails,Flask;jQuery;Vue.js,Just as welcome now as I felt last year,NaN,13,NaN
61561,NaN,Yes,64.0,18,NaN,NaN,NaN,France,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
61570,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61907,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Malaysia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61918,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61983,NaN,Yes,NaN,25,NaN,NaN,NaN,Pakistan,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django;Flask,NaN,NaN,NaN,Less than 1 year,3
62391,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Morocco,NaN,NaN,...,Neither easy nor difficult,Too short,NaN,NaN,Angular.js;Express;React.js;Ruby on Rails,Angular.js;Express;React.js;Ruby on Rails,NaN,NaN,Less than 1 year,Less than 1 year
62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
62605,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62834,NaN,Yes,17.0,10,NaN,NaN,NaN,Canada,NaN,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,7,NaN
62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
63396,NaN,Yes,NaN,24,NaN,NaN,NaN,Monaco,NaN,NaN,...,NaN,NaN,NaN,NaN,Gatsby,Gatsby,NaN,NaN,1,NaN
63452,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,...,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
63796,NaN,Yes,NaN,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
63820,NaN,Yes,NaN,17,NaN,NaN,NaN,Nepal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot less welcome now than last year,NaN,3,NaN
63994,NaN,Yes,NaN,27,NaN,NaN,NaN,Saudi Arabia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot more welcome now than last year,NaN,Less than 1 year,Less than 1 year
64013,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Bulgaria,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,NaN,NaN,NaN
64104,NaN,Yes,NaN,19,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64480,NaN,Yes,NaN,21,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64567,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Netherlands,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET Core,NaN,NaN,NaN,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [44]:
schema

                                                                   QuestionText
Column
Respondent                    Randomized respondent ID number (not in order ...
MainBranch                    Which of the following options best describes ...
Hobbyist                                                Do you code as a hobby?
Age                           What is your age (in years)? If you prefer not...
Age1stCode                    At what age did you write your first line of c...
CompFreq                       Is that compensation weekly, monthly, or yearly?
CompTotal                     What is your current total compensation (salar...
ConvertedComp                 Salary converted to annual USD salaries using ...
Country                                                      Where do you live?
CurrencyDesc                  Which currency do you use day-to-day? If your ...
CurrencySymbol                Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear        Which database environments have you done exte...
DatabaseWorkedWith            Which database environments have you done exte...
DevType                       Which of the following describe you? Please se...
EdLevel                       Which of the following best describes the high...
Employment                    Which of the following best describes your cur...
Ethnicity                     Which of the following describe you, if any? P...
Gender                        Which of the following describe you, if any? P...
JobFactors                    Imagine that you are deciding between two job ...
JobSat                        How satisfied are you with your current job? (...
JobSeek                       Which of the following best describes your cur...
LanguageDesireNextYear        Which programming, scripting, and markup langu...
LanguageWorkedWith            Which programming, scripting, and markup langu...
MiscTechDesireNextYear        Which other frameworks, libraries, and tools h...
MiscTechWorkedWith            Which other frameworks, libraries, and tools h...
NEWCollabToolsDesireNextYear  Which collaboration tools have you done extens...
NEWCollabToolsWorkedWith      Which collaboration tools have you done extens...
NEWDevOps                     Does your company have a dedicated DevOps person?
NEWDevOpsImpt                 How important is the practice of DevOps to sca...
NEWEdImpt                     How important is a formal education, such as a...
...                                                                         ...
NEWJobHuntResearch            When job searching, how do you learn more abou...
NEWLearn                      How frequently do you learn a new language or ...
NEWOffTopic                   Do you think Stack Overflow should relax restr...
NEWOnboardGood                Do you think your company has a good onboardin...
NEWOtherComms                 Are you a member of any other online developer...
NEWOvertime                   How often do you work overtime or beyond the f...
NEWPurchaseResearch           When buying a new tool or software, how do you...
NEWPurpleLink                 You search for a coding solution online and th...
NEWSOSites                    Which of the following Stack Overflow sites ha...
NEWStuck                      What do you do when you get stuck on a problem...
OpSys                         What is the primary operating system in which ...
OrgSize                       Approximately how many people are employed by ...
PlatformDesireNextYear        Which platforms have you done extensive develo...
PlatformWorkedWith            Which platforms have you done extensive develo...
PurchaseWhat                  What level of influence do you, personally, ha...
Sexuality                     Which of the following describe you, if any? P...
SOAccount                                 Do you have a Stack Overflow account?
SOComm                        Do you consider yourself a member of the Stack...
SOPartFreq                    How frequently would you say you participate i...
SOVisitFreq                   How frequently would you say you visit Stack O...
SurveyEase                    How easy or difficult was this survey to compl...
SurveyLength                  How do you feel about the length of the survey...
Trans                                                      Are you transgender?
UndergradMajor                            What was your primary field of study?
WebframeDesireNextYear        Which web frameworks have you done extensive d...
WebframeWorkedWith            Which web frameworks have you done extensive d...
WelcomeChange                 Compared to last year, how welcome do you feel...
WorkWeekHrs                   On average, how many hours per week do you wor...
YearsCode                     Including any education, how many years have y...
YearsCodePro                  NOT including education, how many years have y...

[61 rows x 1 columns]

In [54]:
code = (df['Age1stCode'] > str(14))

In [55]:
df.loc[code]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
12,I am a developer by profession,No,49.0,42,Monthly,1100.0,14268.0,Spain,European Euro,EUR,...,Easy,Appropriate in length,No,Mathematics or statistics,ASP.NET;jQuery,ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,7,7
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
20,I am a developer by profession,Yes,40.0,18,NaN,NaN,NaN,Spain,European Euro,EUR,...,Easy,Too short,No,"Another engineering discipline (such as civil,...",Spring,Angular.js;Spring,Just as welcome now as I felt last year,50.0,22,17
21,I am a student who is learning to code,Yes,23.0,16,NaN,NaN,NaN,Belgium,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Gatsby;React.js;Spring;Vue.js,Angular;ASP.NET Core;Express;React.js;Spring,NaN,NaN,7,NaN
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
25,I am a developer by profession,No,NaN,25,Monthly,NaN,NaN,Portugal,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,23,18
28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
29,I am a student who is learning to code,Yes,18.0,15,NaN,NaN,NaN,Ukraine,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
31,I am a developer by profession,Yes,NaN,20,Weekly,NaN,NaN,Russian Federation,Australian dollar,AUD,...,Easy,Appropriate in length,Yes,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
34,I am a developer by profession,Yes,29.0,15,NaN,NaN,NaN,Germany,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Express;React.js;Spring,Angular;Express,Somewhat more welcome now than last year,NaN,10,NaN
36,"I am not primarily a developer, but I write co...",Yes,34.0,30,Yearly,60000.0,77556.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,4,3
37,I am a developer by profession,Yes,19.0,16,Monthly,NaN,NaN,France,European Euro,EUR,...,Easy,Too long,No,Web development or web design,Gatsby,Express;jQuery;React.js;Vue.js,Somewhat more welcome now than last year,39.0,2,1
39,"I am not primarily a developer, but I write co...",Yes,NaN,17,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,13,1
41,I am a developer by profession,No,NaN,15,Yearly,106000.0,106000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",Vue.js,ASP.NET;Vue.js,A lot less welcome now than last year,40.0,25,20
43,I am a developer by profession,Yes,NaN,16,Yearly,135000.0,135000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,ASP.NET,Just as welcome now as I felt last year,45.0,36,29
44,I am a developer by profession,No,32.0,21,Yearly,244000.0,55893.0,Brazil,Brazilian real,BRL,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,45.0,10,6
48,I am a developer by profession,No,38.0,30,Yearly,125000.0,125000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,Fine arts or performing arts (such as graphic ...,Gatsby;Ruby on Rails,Gatsby;Ruby on Rails,NaN,30.0,8,8
49,I am a developer by profession,No,23.0,15,Yearly,52000.0,52000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,8,4
50,I am a developer by profession,No,57.0,46,NaN,NaN,NaN,Austria,European Euro,EUR,...,Neither easy nor difficult,Too long,No,Fine arts or performing arts (such as graphic ...,jQuery,jQuery,Just as welcome now as I felt last year,35.0,10,9
52,I am a developer by profession,No,28.0,15,Yearly,70000.0,90482.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,35.0,11,6
53,I am a developer by profession,Yes,17.0,9,NaN,NaN,NaN,United States,United States dollar,USD,...,Easy,Appropriate in length,No,NaN,NaN,Flask,A lot less welcome now than last year,5.0,8,3
54,I am a developer by profession,No,44.0,7,Yearly,160000.0,160000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery,Somewhat more welcome now than last year,40.0,38,23
55,I am a student who is learning to code,No,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,Mathematics or statistics,NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55211,NaN,Yes,NaN,31,NaN,NaN,NaN,Pakistan,NaN,NaN,...,Easy,Too short,Yes,"Another engineering discipline (such as civil,...",Angular,Angular,NaN,NaN,6,NaN
56163,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Poland,NaN,NaN,...,Easy,Too short,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,NaN,Less than 1 year,NaN
56661,NaN,Yes,NaN,20,NaN,NaN,NaN,Serbia,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",Django;Laravel;React.js,NaN,Just as welcome now as I felt last year,NaN,4,2
56927,NaN,Yes,17.0,9,NaN,NaN,NaN,Jordan,NaN,NaN,...,Easy,Too long,No,NaN,Django;Express;Flask;Gatsby;jQuery;Laravel;Rea...,Express;Flask;Gatsby;jQuery;React.js,NaN,NaN,3,NaN
57084,NaN,Yes,NaN,18,NaN,NaN,NaN,Sweden,NaN,NaN,...,NaN,NaN,NaN,"A social science (such as anthropology, psycho...",Django;jQuery,Django;jQuery,Just as welcome now as I felt last year,NaN,12,15
57622,NaN,Yes,25.0,18,NaN,NaN,NaN,Bolivia,NaN,NaN,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Angular;Ruby on Rails,Express,Just as welcome now as I felt last year,NaN,4,NaN
57949,NaN,Yes,44.0,15,NaN,NaN,NaN,Belgium,NaN,NaN,...,Neither easy nor difficult,Too long,No,"Another engineering discipline (such as civil,...",ASP.NET;ASP.NET Core;jQuery;React.js;Ruby on R...,NaN,NaN,NaN,Less than 1 year,Less than 1 year
58457,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Djibouti,NaN,NaN,...,Easy,Too short,No,NaN,NaN,Angular;Express,A lot less welcome now than last year,NaN,Less than 1 year,Less than 1 year
58498,NaN,Yes,32.0,23,NaN,NaN,NaN,United States,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,NaN,NaN,8,Less than 1 year
58839,NaN,Yes,NaN,5,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,Easy,Too short,Yes,"A humanities discipline (such as literature, h...",Spring,Spring,NaN,NaN,4,3
59132,NaN,Yes,22.0,16,NaN,NaN,NaN,Mongolia,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",Angular.js;React.js,Angular;Angular.js;React.js,Just as welcome now as I felt last year,NaN,3,Less than 1 year
59168,NaN,Yes,17.0,Younger than 5 years,NaN,NaN,NaN,Costa Rica,NaN,NaN,...,Easy,Too short,NaN,NaN,Drupal;Flask;Gatsby;Spring;Vue.js,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,NaN,14,NaN
59730,NaN,Yes,NaN,55,NaN,NaN,NaN,Austria,NaN,NaN,...,Easy,Too short,NaN,I never declared a major,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,Just as welcome now as I felt last year,NaN,Less than 1 year,NaN
60149,NaN,Yes,34.0,18,NaN,NaN,NaN,Brazil,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django,Just as welcome now as I felt last year,NaN,16,14
60931,NaN,Yes,NaN,17,NaN,NaN,NaN,United States,NaN,NaN,...,Neither easy nor difficult,Too long,No,Web development or web design,NaN,Drupal,Not applicable - I did not use Stack Overflow ...,NaN,5,NaN
61031,NaN,Yes,NaN,23,NaN,NaN,NaN,Spain,NaN,NaN,...,Easy,Appropriate in length,No,NaN,Angular;Angular.js;React.js;Vue.js,Angular;Angular.js,Just as welcome now as I felt last year,NaN,1,1
61111,NaN,Yes,38.0,35,NaN,NaN,NaN,Israel,NaN,NaN,...,Easy,Appropriate in length,No,NaN,React.js,ASP.NET Core;Django;React.js,Somewhat more welcome now than last year,NaN,3,NaN
61561,NaN,Yes,64.0,18,NaN,NaN,NaN,France,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
61983,NaN,Yes,NaN,25,NaN,NaN,NaN,Pakistan,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django;Flask,NaN,NaN,NaN,Less than 1 year,3
62391,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Morocco,NaN,NaN,...,Neither easy nor difficult,Too short,NaN,NaN,Angular.js;Express;React.js;Ruby on Rails,Angular.js;Express;React.js;Ruby on Rails,NaN,NaN,Less than 1 year,Less than 1 year
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
63396,NaN,Yes,NaN,24,NaN,NaN,NaN,Monaco,NaN,NaN,...,NaN,NaN,NaN,NaN,Gatsby,Gatsby,NaN,NaN,1,NaN
63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,...,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
63796,NaN,Yes,NaN,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
63820,NaN,Yes,NaN,17,NaN,NaN,NaN,Nepal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot less welcome now than last year,NaN,3,NaN
63994,NaN,Yes,NaN,27,NaN,NaN,NaN,Saudi Arabia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot more welcome now than last year,NaN,Less than 1 year,Less than 1 year
64104,NaN,Yes,NaN,19,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64480,NaN,Yes,NaN,21,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year

In [58]:
df.loc[code,['Gender','NEWDevOps','EdLevel','Country']]

,Gender,NEWDevOps,EdLevel,Country
Respondent,,,,
2,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United Kingdom
3,NaN,NaN,NaN,Russian Federation
4,Man,No,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Albania
5,Man,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
7,NaN,Yes,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",India
9,Man,NaN,"Professional degree (JD, MD, etc.)",Tunisia
12,Man,Not sure,Some college/university study without earning ...,Spain
16,Man,No,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United Kingdom
19,Man,Yes,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
20,Man,Yes,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Spain
21,Man,NaN,"Secondary school (e.g. American high school, G...",Belgium
22,Man,Not sure,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",India
25,Man,No,"Associate degree (A.A., A.S., etc.)",Portugal
28,Man,NaN,Some college/university study without earning ...,China
29,Man,NaN,"Secondary school (e.g. American high school, G...",Ukraine
31,Man,Yes,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Russian Federation
34,Man,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Germany
36,Man,Not sure,Some college/university study without earning ...,United Kingdom
37,Man,Yes,"Associate degree (A.A., A.S., etc.)",France
39,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United Kingdom
41,NaN,No,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States
43,NaN,Yes,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States
44,Man,No,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Brazil
48,Man,Yes,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
49,Man,Yes,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
50,Man,No,Some college/university study without earning ...,Austria
52,Man,No,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United Kingdom
53,Man,NaN,"Secondary school (e.g. American high school, G...",United States
54,Man,No,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
55,Man,NaN,"Associate degree (A.A., A.S., etc.)",United States
...,...,...,...,...
55211,Man,NaN,"Professional degree (JD, MD, etc.)",Pakistan
56163,Woman,NaN,I never completed any formal education,Poland
56661,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Serbia
56927,Man,NaN,Primary/elementary school,Jordan
57084,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Sweden
57622,Man,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bolivia
57949,Man,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Belgium
58457,Man,NaN,I never completed any formal education,Djibouti
58498,Man,NaN,Some college/university study without earning ...,United States
58839,Man,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bangladesh
59132,Man,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Mongolia
59168,"Non-binary, genderqueer, or gender non-conforming",NaN,"Secondary school (e.g. American high school, G...",Costa Rica
59730,Man,NaN,Some college/university study without earning ...,Austria
60149,Man,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Brazil
60931,Man,NaN,Some college/university study without earning ...,United States
61031,Man,NaN,"Secondary school (e.g. American high school, G...",Spain
61111,Man,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Israel
61561,Man,NaN,NaN,France
61983,Man,NaN,"Secondary school (e.g. American high school, G...",Pakistan
62391,Man,NaN,Primary/elementary school,Morocco
63077,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States
63396,NaN,NaN,"Secondary school (e.g. American high school, G...",Monaco
63640,Man,NaN,Primary/elementary school,Australia
63796,NaN,NaN,NaN,Bangladesh
63820,NaN,NaN,"Secondary school (e.g. American high school, G...",Nepal
63994,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Saudi Arabia
64104,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Poland
64330,NaN,NaN,Primary/elementary school,Thailand
64480,NaN,NaN,I never completed any formal education,Morocco
64858,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States

In [60]:
countries=['United States','Morocco','Poland']
filt=df['Country'].isin(countries)

In [65]:
df.loc[filt,['Country','Gender']]

                  Country                                             Gender
Respondent
5           United States                                                Man
8           United States                                                Man
14          United States                                                Man
17          United States                                                Man
18          United States                                                Man
19          United States                                                Man
27          United States                                                Man
35          United States                                              Woman
40          United States                                              Woman
41          United States                                                NaN
42          United States                                                Man
43          United States                                                NaN
48          United States                                                Man
49          United States                                                Man
53          United States                                                Man
54          United States                                                Man
55          United States                                                Man
56          United States                                              Woman
57          United States                                                Man
65          United States                                                Man
67          United States                                                Man
68          United States                                                Man
72          United States                                                Man
76          United States                                                Man
77          United States                                                Man
80          United States                                                Man
81          United States                                                Man
82          United States                                                Man
83                 Poland                                                Man
84          United States                                                Man
...                   ...                                                ...
34097       United States  Non-binary, genderqueer, or gender non-conforming
35969       United States                                                NaN
36370       United States                                                NaN
37011       United States                                                NaN
38665              Poland                                                NaN
38893              Poland                                                NaN
39520             Morocco                                                NaN
42314       United States                                                NaN
43211       United States                                                NaN
44176       United States                                                NaN
45374       United States                                                NaN
45440       United States                                                NaN
45721       United States                                                Man
49544       United States                                                Man
52304       United States                                                Man
53549       United States                                                Man
53697       United States                                                Man
54068       United States                                                Man
54361       United States                                                Man
56163              Poland                                              Woman
58498       United States                                                Man
58896       United States                                                Man
60931       United States                                                Man
62391             Morocco                                                Man
63077       United States                                                NaN
64104              Poland                                                NaN
64480             Morocco                                                NaN
64858       United States                                                NaN
64867             Morocco                                                NaN
64925              Poland                                                NaN

[13923 rows x 2 columns]

In [67]:
filt=df['LanguageWorkedWith'].str.contains('Python',na=False)

In [69]:
df.loc[filt,'LanguageWorkedWith']

Respondent
3                                 Objective-C;Python;Swift
8                                               Python;SQL
10                     HTML/CSS;Java;JavaScript;Python;SQL
13                                     C;JavaScript;Python
15        Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
17                   C#;HTML/CSS;JavaScript;Python;SQL;VBA
22                                             Java;Python
26                                       JavaScript;Python
27             Bash/Shell/PowerShell;C;C++;Java;Python;SQL
28                                                Python;R
29                                  C#;C++;HTML/CSS;Python
30       Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
32                               C;C++;Java;Python;SQL;VBA
36             C#;Go;HTML/CSS;Java;JavaScript;Python;R;SQL
38                    HTML/CSS;JavaScript;Python;Ruby;Rust
39                                               C#;Python
40             C;C#;C++;HTML/CSS;JavaScript;PHP;Python;SQL
42       Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
44                               HTML/CSS;Python;R;SQL;VBA
45       Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...
47       Bash/Shell/PowerShell;C#;Java;JavaScript;Pytho...
51                        JavaScript;Python;SQL;TypeScript
53                                    Dart;HTML/CSS;Python
55                                                  Python
56           HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript
60                  C#;HTML/CSS;Java;JavaScript;Python;SQL
62              C#;C++;HTML/CSS;Java;Python;Ruby;SQL;Swift
63                   C;C++;HTML/CSS;Java;JavaScript;Python
66       Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...
68       Assembly;Bash/Shell/PowerShell;C;C#;HTML/CSS;J...
                               ...
49544      Bash/Shell/PowerShell;JavaScript;Python;SQL;VBA
52163    C;C++;Go;HTML/CSS;JavaScript;Perl;PHP;Python;R...
52184                                JavaScript;Python;SQL
52304    Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...
52582    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
53549    Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...
53697                   Bash/Shell/PowerShell;Python;R;SQL
54068    Bash/Shell/PowerShell;C;C++;Haskell;JavaScript...
54361    Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
54757            C;HTML/CSS;Java;JavaScript;PHP;Python;SQL
55074    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
56163    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
56263    Assembly;C;C#;Haskell;Java;Kotlin;PHP;Python;R...
56661                                          Java;Python
56927    Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Py...
57084          C;HTML/CSS;Java;JavaScript;Python;R;SQL;VBA
58498    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
59132    Assembly;C++;HTML/CSS;Java;JavaScript;Python;T...
59168    Assembly;C;C#;C++;Go;HTML/CSS;Java;JavaScript;...
59638                                      HTML/CSS;Python
60134    Assembly;C;C++;Dart;HTML/CSS;Java;Kotlin;Pytho...
60149                                           Python;SQL
61031             Dart;JavaScript;Kotlin;Python;TypeScript
61111                           HTML/CSS;JavaScript;Python
61490    Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;JavaSc...
61561    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...
62391       C++;HTML/CSS;JavaScript;Python;Ruby;TypeScript
63077              C++;HTML/CSS;Java;JavaScript;Python;SQL
63640    Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...
64867    Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
Name: LanguageWorkedWith, Length: 25287, dtype: object

In [71]:
df.loc[filt]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
13,"I am not primarily a developer, but I write co...",Yes,53.0,14,Monthly,3000.0,38916.0,Netherlands,European Euro,EUR,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20
15,I am a student who is learning to code,Yes,NaN,13,NaN,NaN,NaN,France,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
26,I am a developer by profession,No,NaN,12,Yearly,94000.0,71093.0,Canada,Canadian dollar,CAD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,Django;React.js,Just as welcome now as I felt last year,40.0,17,10
27,"I used to be a developer by profession, but no...",Yes,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",Flask,Flask,Just as welcome now as I felt last year,NaN,20,20
28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
29,I am a student who is learning to code,Yes,18.0,15,NaN,NaN,NaN,Ukraine,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
30,I am a developer by profession,Yes,NaN,14,Yearly,30000.0,38778.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Express;React.js;Vue.js,Express;Vue.js,A lot less welcome now than last year,37.0,4,2
32,I am a developer by profession,Yes,31.0,12,Monthly,3500.0,31764.0,Canada,Canadian dollar,CAD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,37.0,19,10
36,"I am not primarily a developer, but I write co...",Yes,34.0,30,Yearly,60000.0,77556.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,4,3
38,I am a developer by profession,No,35.0,14,Yearly,90000.0,97288.0,Italy,European Euro,EUR,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js,Express;Gatsby;React.js,Just as welcome now as I felt last year,40.0,20,12
39,"I am not primarily a developer, but I write co...",Yes,NaN,17,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,13,1
40,I am a student who is learning to code,Yes,20.0,14,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,6,NaN
42,I am a developer by profession,No,32.0,14,Yearly,130000.0,130000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Spring,ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
44,I am a developer by profession,No,32.0,21,Yearly,244000.0,55893.0,Brazil,Brazilian real,BRL,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,45.0,10,6
45,I am a developer by profession,Yes,22.0,13,Yearly,34000.0,36753.0,France,European Euro,EUR,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Angular;Flask,Angular;Flask;jQuery;Spring,A lot less welcome now than last year,35.0,9,2
47,I am a developer by profession,Yes,53.0,10,Yearly,58000.0,74970.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Flask;Spring,Flask;Spring,Just as welcome now as I felt last year,40.0,43,28
51,I am a developer by profession,No,NaN,10,Yearly,137000.0,103615.0,Canada,Canadian dollar,CAD,...,Difficult,Too long,NaN,I never declared a major,NaN,Django;React.js,Just as welcome now as I felt last year,35.0,23,7
53,I am a developer by profession,Yes,17.0,9,NaN,NaN,NaN,United States,United States dollar,USD,...,Easy,Appropriate in length,No,NaN,NaN,Flask,A lot less welcome now than last year,5.0,8,3
55,I am a student who is learning to code,No,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,Mathematics or statistics,NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
56,I am a developer by profession,Yes,27.0,21,NaN,NaN,NaN,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Django,Symfony,Just as welcome now as I felt last year,40.0,6,4
60,I am a student who is learning to code,Yes,NaN,14,NaN,NaN,NaN,Germany,NaN,NaN,...,Easy,Appropriate in length,No,NaN,Django,NaN,Just as welcome now as I felt last year,NaN,2,NaN
62,I am a student who is learning to code,No,20.0,11,NaN,NaN,NaN,United Kingdom,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;jQuery;Ruby on Rails,NaN,Just as welcome now as I felt last year,NaN,7,NaN
63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
66,I am a developer by profession,Yes,21.0,9,NaN,NaN,NaN,Canada,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Django;jQuery,Not applicable - I did not use Stack Overflow ...,NaN,12,NaN
68,I am a student who is learning to code,Yes,20.0,10,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core;Django;Flask;Laravel,NaN,Just as welcome now as I felt last year,NaN,10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49544,NaN,Yes,32.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"A business discipline (such as accounting, fin...",Flask;Vue.js,Express;Flask,Just as welcome now as I felt last year,NaN,14,10
52163,NaN,Yes,NaN,14,NaN,NaN,NaN,Germany,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",React.js,React.js,Just as welcome now as I felt last year,NaN,7,NaN
52184,NaN,Yes,20.0,17,NaN,NaN,NaN,India,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;jQuery;Ruby on Rails;Vue.js,Django;Flask;React.js,Just as welcome now as I felt last year,NaN,3,NaN
52304,NaN,Yes,NaN,6,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,Flask;jQuery,Just as welcome now as I felt last year,NaN,14,NaN
52582,NaN,Yes,1.0,Younger than 5 years,NaN,NaN,NaN,Indonesia,NaN,NaN,...,Easy,Too short,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,NaN,1,1
53549,NaN,Yes,26.0,21,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;React.js;Ruby on Rails,Angular;ASP.NET;ASP.NET Core;Django;Spring,Just as welcome now as I felt last year,NaN,5,1
53697,NaN,Yes,30.0,24,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"A social science (such as anthropology, psycho...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
54068,NaN,Yes,24.0,12,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,Mathematics or statistics,React.js,React.js,Just as welcome now as I felt last year,NaN,12,NaN
54361,NaN,Yes,56.0,50,NaN,NaN,NaN,United States,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"A health science (such as nursing, pharmacy, r...",NaN,ASP.NET;jQuery,Not applicable - I did not use Stack Overflow ...,NaN,2,NaN
54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
55074,NaN,Yes,36.0,35,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,Easy,Appropriate in length,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,A lot less welcome now than last year,NaN,Less than 1 year,12
56163,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Poland,NaN,NaN,...,Easy,Too short,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,NaN,Less than 1 year,NaN
56263,NaN,Yes,NaN,14,NaN,NaN,NaN,Germany,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,7,NaN
56661,NaN,Yes,NaN,20,NaN,NaN,NaN,Serbia,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",Django;Laravel;React.js,NaN,Just as welcome now as I felt last year,NaN,4,2
56927,NaN,Yes,17.0,9,NaN,NaN,NaN,Jordan,NaN,NaN,...,Easy,Too long,No,NaN,Django;Express;Flask;Gatsby;jQuery;Laravel;Rea...,Express;Flask;Gatsby;jQuery;React.js,NaN,NaN,3,NaN
57084,NaN,Yes,NaN,18,NaN,NaN,NaN,Sweden,NaN,NaN,...,NaN,NaN,NaN,"A social science (such as anthropology, psycho...",Django;jQuery,Django;jQuery,Just as welcome now as I felt last year,NaN,12,15
58498,NaN,Yes,32.0,23,NaN,NaN,NaN,United States,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,ASP.NET;ASP.NET Core;Flask;Gatsby;jQuery;React...,NaN,NaN,8,Less than 1 year
59132,NaN,Yes,22.0,16,NaN,NaN,NaN,Mongolia,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",Angular.js;React.js,Angular;Angular.js;React.js,Just as welcome now as I felt last year,NaN,3,Less than 1 year
59168,NaN,Yes,17.0,Younger than 5 years,NaN,NaN,NaN,Costa Rica,NaN,NaN,...,Easy,Too short,NaN,NaN,Drupal;Flask;Gatsby;Spring;Vue.js,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,NaN,14,NaN
59638,NaN,Yes,23.0,10,NaN,NaN,NaN,United Kingdom,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask;React.js;Spring,Django;Flask,Just as welcome now as I felt last year,NaN,5,NaN
60134,NaN,Yes,22.0,10,NaN,NaN,NaN,Spain,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;React.js;Spring,Just as welcome now as I felt last year,NaN,10,NaN
60149,NaN,Yes,34.0,18,NaN,NaN,NaN,Brazil,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django,Just as welcome now as I felt last year,NaN,16,14
61031,NaN,Yes,NaN,23,NaN,NaN,NaN,Spain,NaN,NaN,...,Easy,Appropriate in length,No,NaN,Angular;Angular.js;React.js;Vue.js,Angular;Angular.js,Just as welcome now as I felt last year,NaN,1,1
61111,NaN,Yes,38.0,35,NaN,NaN,NaN,Israel,NaN,NaN,...,Easy,Appropriate in length,No,NaN,React.js,ASP.NET Core;Django;React.js,Somewhat more welcome now than last year,NaN,3,NaN
61490,NaN,Yes,NaN,14,NaN,NaN,NaN,United Kingdom,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Ruby on Rails,Flask;jQuery;Vue.js,Just as welcome now as I felt last year,NaN,13,NaN
61561,NaN,Yes,64.0,18,NaN,NaN,NaN,France,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
62391,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Morocco,NaN,NaN,...,Neither easy nor difficult,Too short,NaN,NaN,Angular.js;Express;React.js;Ruby on Rails,Angular.js;Express;React.js;Ruby on Rails,NaN,NaN,Less than 1 year,Less than 1 year
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,...,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
filt=(df['Country']=='United States') & (df['Gender']=='Man')

In [86]:
df.loc[filt,['Respondent','Country','Hobbyist']]

            Respondent        Country Hobbyist
Respondent
5                  NaN  United States      Yes
8                  NaN  United States      Yes
14                 NaN  United States      Yes
17                 NaN  United States      Yes
18                 NaN  United States      Yes
19                 NaN  United States       No
27                 NaN  United States      Yes
42                 NaN  United States       No
48                 NaN  United States       No
49                 NaN  United States       No
53                 NaN  United States      Yes
54                 NaN  United States       No
55                 NaN  United States       No
57                 NaN  United States       No
65                 NaN  United States      Yes
67                 NaN  United States      Yes
68                 NaN  United States      Yes
72                 NaN  United States      Yes
76                 NaN  United States      Yes
77                 NaN  United States      Yes
80                 NaN  United States      Yes
81                 NaN  United States      Yes
82                 NaN  United States      Yes
84                 NaN  United States      Yes
103                NaN  United States      Yes
105                NaN  United States      Yes
109                NaN  United States      Yes
110                NaN  United States       No
112                NaN  United States      Yes
113                NaN  United States      Yes
...                ...            ...      ...
62882              NaN  United States      Yes
62886              NaN  United States      Yes
62888              NaN  United States      Yes
62893              NaN  United States      Yes
62895              NaN  United States      Yes
62901              NaN  United States      Yes
62904              NaN  United States      Yes
62907              NaN  United States      Yes
62908              NaN  United States      Yes
63372              NaN  United States      Yes
63387              NaN  United States       No
63420              NaN  United States      Yes
64810              NaN  United States      Yes
65629              NaN  United States      Yes
889                NaN  United States      Yes
2331               NaN  United States      Yes
2902               NaN  United States      Yes
17530              NaN  United States      Yes
18541              NaN  United States      Yes
19581              NaN  United States      Yes
45721              NaN  United States      Yes
49544              NaN  United States      Yes
52304              NaN  United States      Yes
53549              NaN  United States      Yes
53697              NaN  United States      Yes
54068              NaN  United States      Yes
54361              NaN  United States      Yes
58498              NaN  United States      Yes
58896              NaN  United States      Yes
60931              NaN  United States      Yes

[9176 rows x 3 columns]